package dev.obiente.nextcloudnative.app

import dev.obiente.nextcloudnative.app.design.NextcloudPresentation

enum class MarketingCapturePurpose(val manifestValue: String) {
    Showcase("showcase"),
    StateCoverage("state-coverage"),
}

enum class MarketingCaptureTheme(
    val manifestValue: String,
    val darkTheme: Boolean,
) {
    Dark("dark", true),
    Light("light", false),
}

enum class MarketingCaptureScenario(
    val id: String,
    val fileName: String,
    val presentation: NextcloudPresentation,
    val feature: String,
    val surface: String,
    val state: String,
    val purpose: MarketingCapturePurpose,
    val platform: String,
    val viewport: String,
    val pullRequest: Int? = null,
    val issue: Int? = null,
    val width: Int,
    val height: Int,
    val density: Float,
    val darkTheme: Boolean = true,
) {
    SharedControlsDesktop(
        "shared-controls-desktop", "shared-controls-desktop.png", NextcloudPresentation.Desktop,
        "Shared UI", "Choice controls", "Views, filters and form states", MarketingCapturePurpose.StateCoverage,
        "desktop", "wide", width = 1_280, height = 900, density = 1f,
    ),
    SharedControlsMobile(
        "shared-controls-mobile", "shared-controls-mobile.png", NextcloudPresentation.Adaptive,
        "Shared UI", "Choice controls", "Compact views, filters and form states", MarketingCapturePurpose.StateCoverage,
        "android", "phone", width = 1_080, height = 2_400, density = 3f,
    ),
    ShellCompactDesktop(
        "shell-compact-desktop", "shell-compact-desktop.png", NextcloudPresentation.Desktop,
        "App shell", "Compact sidebar", "Editing an event", MarketingCapturePurpose.StateCoverage,
        "desktop", "compact", width = 820, height = 800, density = 1f,
    ),
    ShellAppSwitcherMobile(
        "shell-app-switcher-mobile", "shell-app-switcher-mobile.png", NextcloudPresentation.Adaptive,
        "App shell", "App switcher", "Pinned and installed apps", MarketingCapturePurpose.StateCoverage,
        "android", "phone", width = 1_080, height = 2_400, density = 3f,
    ),
    ShellTablet(
        "shell-tablet", "shell-tablet.png", NextcloudPresentation.Adaptive,
        "App shell", "Tablet navigation", "Editing an event", MarketingCapturePurpose.StateCoverage,
        "android", "tablet", width = 1_680, height = 1_600, density = 2f,
    ),
    HomepageOverviewDesktopDark(
        "homepage-overview-desktop-dark",
        "homepage-overview-desktop-dark.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Complete account overview",
        "Ready",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
    ),
    HomepageOverviewDesktopLight(
        "homepage-overview-desktop-light",
        "homepage-overview-desktop-light.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Complete account overview",
        "Ready",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
        darkTheme = false,
    ),
    HomepageOverviewMobileDark(
        "homepage-overview-mobile-dark",
        "homepage-overview-mobile-dark.png",
        NextcloudPresentation.Adaptive,
        "Homepage",
        "Complete account overview",
        "Ready",
        MarketingCapturePurpose.Showcase,
        "mobile",
        "phone-portrait",
        width = 1_080,
        height = 2_400,
        density = 2.625f,
    ),
    HomepageOverviewMobileLight(
        "homepage-overview-mobile-light",
        "homepage-overview-mobile-light.png",
        NextcloudPresentation.Adaptive,
        "Homepage",
        "Complete account overview",
        "Ready",
        MarketingCapturePurpose.Showcase,
        "mobile",
        "phone-portrait",
        width = 1_080,
        height = 2_400,
        density = 2.625f,
        darkTheme = false,
    ),
    HomepageFilesDesktopDark(
        "homepage-files-desktop-dark",
        "homepage-files-desktop-dark.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Files workspace",
        "Synced with offline content",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
    ),
    HomepageFilesDesktopLight(
        "homepage-files-desktop-light",
        "homepage-files-desktop-light.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Files workspace",
        "Synced with offline content",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
        darkTheme = false,
    ),
    HomepageFilesMobileDark(
        "homepage-files-mobile-dark",
        "homepage-files-mobile-dark.png",
        NextcloudPresentation.Adaptive,
        "Homepage",
        "Files workspace",
        "Synced with offline content",
        MarketingCapturePurpose.Showcase,
        "mobile",
        "phone-portrait",
        width = 1_080,
        height = 2_400,
        density = 2.625f,
    ),
    HomepageFilesMobileLight(
        "homepage-files-mobile-light",
        "homepage-files-mobile-light.png",
        NextcloudPresentation.Adaptive,
        "Homepage",
        "Files workspace",
        "Synced with offline content",
        MarketingCapturePurpose.Showcase,
        "mobile",
        "phone-portrait",
        width = 1_080,
        height = 2_400,
        density = 2.625f,
        darkTheme = false,
    ),
    HomepagePhotosDesktopDark(
        "homepage-photos-desktop-dark",
        "homepage-photos-desktop-dark.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Photos and memories workspace",
        "Library ready",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
    ),
    HomepagePhotosDesktopLight(
        "homepage-photos-desktop-light",
        "homepage-photos-desktop-light.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Photos and memories workspace",
        "Library ready",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
        darkTheme = false,
    ),
    HomepageConversationsDesktopDark(
        "homepage-conversations-desktop-dark",
        "homepage-conversations-desktop-dark.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Conversation workspace",
        "Active conversation",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
    ),
    HomepageConversationsDesktopLight(
        "homepage-conversations-desktop-light",
        "homepage-conversations-desktop-light.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Conversation workspace",
        "Active conversation",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
        darkTheme = false,
    ),
    HomepagePlanningDesktopDark(
        "homepage-planning-desktop-dark",
        "homepage-planning-desktop-dark.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Planning workspace",
        "Board ready",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
    ),
    HomepagePlanningDesktopLight(
        "homepage-planning-desktop-light",
        "homepage-planning-desktop-light.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Planning workspace",
        "Board ready",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
        darkTheme = false,
    ),
    HomepageAppsDesktopDark(
        "homepage-apps-desktop-dark",
        "homepage-apps-desktop-dark.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Installed app workspace",
        "Verified native data",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
    ),
    HomepageAppsDesktopLight(
        "homepage-apps-desktop-light",
        "homepage-apps-desktop-light.png",
        NextcloudPresentation.Desktop,
        "Homepage",
        "Installed app workspace",
        "Verified native data",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
        darkTheme = false,
    ),
    AppsWorkspaceDesktopDark(
        "apps-workspace-desktop-dark",
        "apps-workspace-desktop-dark.png",
        NextcloudPresentation.Desktop,
        "Apps",
        "Installed app command center",
        "Active account with pinned and recent workspaces",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
    ),
    AppsWorkspaceDesktopLight(
        "apps-workspace-desktop-light",
        "apps-workspace-desktop-light.png",
        NextcloudPresentation.Desktop,
        "Apps",
        "Installed app command center",
        "Active account with pinned and recent workspaces",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        width = 1_440,
        height = 900,
        density = 1f,
        darkTheme = false,
    ),
    CalendarWorkspaceDesktopDark(
        "calendar-workspace-desktop-dark",
        "calendar-workspace-desktop-dark.png",
        NextcloudPresentation.Desktop,
        "Calendar",
        "Month planning workspace",
        "Four calendars, selected event, and active month",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        pullRequest = 273,
        width = 1_440,
        height = 900,
        density = 1f,
    ),
    CalendarWorkspaceDesktopLight(
        "calendar-workspace-desktop-light",
        "calendar-workspace-desktop-light.png",
        NextcloudPresentation.Desktop,
        "Calendar",
        "Month planning workspace",
        "Four calendars, selected event, and active month",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        pullRequest = 273,
        width = 1_440,
        height = 900,
        density = 1f,
        darkTheme = false,
    ),
    CalendarWorkspaceMobileDark(
        "calendar-workspace-mobile-dark",
        "calendar-workspace-mobile-dark.png",
        NextcloudPresentation.Adaptive,
        "Calendar",
        "Mobile agenda",
        "Active week with personal, team, and community events",
        MarketingCapturePurpose.Showcase,
        "mobile",
        "phone-portrait",
        pullRequest = 273,
        width = 1_080,
        height = 1_800,
        density = 2.625f,
    ),
    CalendarWorkspaceMobileLight(
        "calendar-workspace-mobile-light",
        "calendar-workspace-mobile-light.png",
        NextcloudPresentation.Adaptive,
        "Calendar",
        "Mobile agenda",
        "Active week with personal, team, and community events",
        MarketingCapturePurpose.Showcase,
        "mobile",
        "phone-portrait",
        pullRequest = 273,
        width = 1_080,
        height = 1_800,
        density = 2.625f,
        darkTheme = false,
    ),
    CalendarMonthMobile(
        "calendar-month-mobile", "calendar-month-mobile.png", NextcloudPresentation.Adaptive,
        "Calendar", "Mobile month", "Selected date with writable and read-only sources",
        MarketingCapturePurpose.Showcase, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    CalendarEventEditorMobile(
        "calendar-event-editor-mobile", "calendar-event-editor-mobile.png", NextcloudPresentation.Adaptive,
        "Calendar", "Mobile event editor", "Existing event with date, time, and recurrence controls",
        MarketingCapturePurpose.Showcase, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    CalendarWeekMobile(
        "calendar-week-mobile", "calendar-week-mobile.png", NextcloudPresentation.Adaptive,
        "Calendar", "Mobile week", "Selected day and event schedule",
        MarketingCapturePurpose.Showcase, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    CalendarWeekDesktop(
        "calendar-week-desktop", "calendar-week-desktop.png", NextcloudPresentation.Desktop,
        "Calendar", "Desktop week", "Scrollable day columns and event inspector",
        MarketingCapturePurpose.Showcase, "desktop", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    CalendarEventEditorDesktop(
        "calendar-event-editor-desktop", "calendar-event-editor-desktop.png", NextcloudPresentation.Desktop,
        "Calendar", "Desktop event editor", "Existing event with date, time, and recurrence controls",
        MarketingCapturePurpose.Showcase, "desktop", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    DesktopHome(
        "desktop-home", "desktop-home.png", NextcloudPresentation.Desktop,
        "Workspace", "Home dashboard", "Ready", MarketingCapturePurpose.Showcase,
        "desktop", "wide", width = 1_440, height = 900, density = 1f,
    ),
    MobileHome(
        "mobile-home", "mobile-home.png", NextcloudPresentation.Adaptive,
        "Workspace", "Home dashboard", "Ready", MarketingCapturePurpose.Showcase,
        "mobile", "phone-portrait", width = 1_080, height = 2_400, density = 2.625f,
    ),
    ObsidianSync(
        "obsidian-vault-sync", "obsidian-vault-sync.png", NextcloudPresentation.Adaptive,
        "File sync", "Folder pair", "One pending upload", MarketingCapturePurpose.Showcase,
        "mobile", "phone-compact", width = 1_080, height = 1_000, density = 2.625f,
    ),
    MediaBackup(
        "media-backup-queue", "media-backup-queue.png", NextcloudPresentation.Adaptive,
        "Media backup", "Folder discovery", "Ready with pending uploads",
        MarketingCapturePurpose.Showcase, "mobile", "phone-portrait",
        width = 1_080, height = 2_200, density = 2.625f,
    ),
    FileSyncRulesMobile(
        "file-sync-rules-mobile", "file-sync-rules-mobile.png", NextcloudPresentation.Adaptive,
        "File sync", "Folder pair configuration", "Selective, ignore, and priority rules",
        MarketingCapturePurpose.StateCoverage, "mobile", "phone-portrait",
        width = 1_080, height = 2_200, density = 2.625f,
    ),
    FileSyncStatusMobile(
        "file-sync-status-mobile", "file-sync-status-mobile.png", NextcloudPresentation.Adaptive,
        "File sync", "Folder sync center", "Conflict recovery and mapping health",
        MarketingCapturePurpose.StateCoverage, "mobile", "phone-portrait",
        width = 1_080, height = 2_200, density = 2.625f,
    ),
    FileSyncStatusDesktop(
        "file-sync-status-desktop", "file-sync-status-desktop.png", NextcloudPresentation.Desktop,
        "File sync", "Folder sync center", "Priority queue, conflict, and failure",
        MarketingCapturePurpose.Showcase, "linux", "wide",
        width = 1_440, height = 1_145, density = 1f,
    ),
    ActivityWorkspaceDesktop(
        "activity-workspace-desktop", "activity-workspace-desktop.png", NextcloudPresentation.Desktop,
        "Activity", "Attention-first activity workspace", "Grouped automation and actionable events",
        MarketingCapturePurpose.Showcase, "desktop", "wide",
        width = 1_721, height = 914, density = 1f,
    ),
    ActivityWorkspaceMobileDark(
        "activity-workspace-mobile-dark", "activity-workspace-mobile-dark.png", NextcloudPresentation.Adaptive,
        "Activity", "Attention-first activity workspace", "Actionable events and compact filters",
        MarketingCapturePurpose.Showcase, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    ActivityWorkspaceMobileLight(
        "activity-workspace-mobile-light", "activity-workspace-mobile-light.png", NextcloudPresentation.Adaptive,
        "Activity", "Attention-first activity workspace", "Actionable events and compact filters",
        MarketingCapturePurpose.Showcase, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f, darkTheme = false,
    ),
    BudgetDashboardDesktopDark(
        "budget-dashboard-desktop-dark", "budget-dashboard-desktop-dark.png", NextcloudPresentation.Desktop,
        "Budget", "Finance dashboard", "Verified account, transaction, budget, bill, and goal data",
        MarketingCapturePurpose.Showcase, "desktop", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    BudgetDashboardDesktopLight(
        "budget-dashboard-desktop-light", "budget-dashboard-desktop-light.png", NextcloudPresentation.Desktop,
        "Budget", "Finance dashboard", "Verified account, transaction, budget, bill, and goal data",
        MarketingCapturePurpose.Showcase, "desktop", "wide",
        width = 1_440, height = 900, density = 1f, darkTheme = false,
    ),
    BudgetDashboardMobileDark(
        "budget-dashboard-mobile-dark", "budget-dashboard-mobile-dark.png", NextcloudPresentation.Adaptive,
        "Budget", "Finance dashboard", "Progressive compact finance overview",
        MarketingCapturePurpose.Showcase, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    BudgetDashboardMobileLight(
        "budget-dashboard-mobile-light", "budget-dashboard-mobile-light.png", NextcloudPresentation.Adaptive,
        "Budget", "Finance dashboard", "Progressive compact finance overview",
        MarketingCapturePurpose.Showcase, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f, darkTheme = false,
    ),
    BudgetTransactionsDesktop(
        "budget-transactions-desktop", "budget-transactions-desktop.png", NextcloudPresentation.Desktop,
        "Budget", "Transactions", "Synthetic records from GET /apps/budget/api/transactions",
        MarketingCapturePurpose.StateCoverage, "desktop", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    BudgetTransactionsMobile(
        "budget-transactions-mobile", "budget-transactions-mobile.png", NextcloudPresentation.Adaptive,
        "Budget", "Transactions", "Synthetic records from GET /apps/budget/api/transactions",
        MarketingCapturePurpose.StateCoverage, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    BudgetAccountsDesktop(
        "budget-accounts-desktop", "budget-accounts-desktop.png", NextcloudPresentation.Desktop,
        "Budget", "Accounts", "Synthetic records from GET /apps/budget/api/accounts",
        MarketingCapturePurpose.StateCoverage, "desktop", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    BudgetAccountsMobile(
        "budget-accounts-mobile", "budget-accounts-mobile.png", NextcloudPresentation.Adaptive,
        "Budget", "Accounts", "Synthetic records from GET /apps/budget/api/accounts",
        MarketingCapturePurpose.StateCoverage, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    BudgetCategoriesDesktop(
        "budget-categories-desktop", "budget-categories-desktop.png", NextcloudPresentation.Desktop,
        "Budget", "Categories", "Synthetic data from verified Budget category API routes",
        MarketingCapturePurpose.StateCoverage, "desktop", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    BudgetCategoriesMobile(
        "budget-categories-mobile", "budget-categories-mobile.png", NextcloudPresentation.Adaptive,
        "Budget", "Categories", "Synthetic data from verified Budget category API routes",
        MarketingCapturePurpose.StateCoverage, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    BudgetPlanDesktop(
        "budget-plan-desktop", "budget-plan-desktop.png", NextcloudPresentation.Desktop,
        "Budget", "Budget plan", "Synthetic report from GET /apps/budget/api/reports/budget",
        MarketingCapturePurpose.StateCoverage, "desktop", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    BudgetPlanMobile(
        "budget-plan-mobile", "budget-plan-mobile.png", NextcloudPresentation.Adaptive,
        "Budget", "Budget plan", "Synthetic report from GET /apps/budget/api/reports/budget",
        MarketingCapturePurpose.StateCoverage, "mobile", "phone-portrait",
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    FileSyncSetupDesktop(
        "file-sync-setup-desktop", "file-sync-setup-desktop.png", NextcloudPresentation.Desktop,
        "File sync", "Folder pair configuration", "Guided RAW-first setup",
        MarketingCapturePurpose.StateCoverage, "linux", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    FileSyncSelectionDesktop(
        "file-sync-selection-desktop", "file-sync-selection-desktop.png", NextcloudPresentation.Desktop,
        "File sync", "Selective sync browser", "Verified folders and files",
        MarketingCapturePurpose.StateCoverage, "linux", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    FileSyncSelectionMobile(
        "file-sync-selection-mobile", "file-sync-selection-mobile.png", NextcloudPresentation.Adaptive,
        "File sync", "Selective sync browser", "Verified folders and files",
        MarketingCapturePurpose.StateCoverage, "mobile", "phone-portrait",
        width = 1_080, height = 2_200, density = 2.625f,
    ),
    VirtualFileStorageMobile(
        "virtual-file-storage-mobile", "virtual-file-storage-mobile.png", NextcloudPresentation.Adaptive,
        "Virtual files", "Storage rules", "Automatic cleanup with protected pins",
        MarketingCapturePurpose.StateCoverage, "mobile", "phone-portrait",
        width = 1_080, height = 2_200, density = 2.625f,
    ),
    VirtualFileStorageDesktop(
        "virtual-file-storage-desktop", "virtual-file-storage-desktop.png", NextcloudPresentation.Desktop,
        "Virtual files", "Storage overview", "Hydrated cache, pins, and free-up action",
        MarketingCapturePurpose.StateCoverage, "linux", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    WindowsCloudFilesStorageDesktop(
        "windows-cloud-files-storage-desktop", "windows-cloud-files-storage-desktop.png",
        NextcloudPresentation.Desktop, "Windows Cloud Files", "File Explorer storage", "Active placeholders, hydrated files, and pins",
        MarketingCapturePurpose.Showcase, "windows", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    WindowsCloudFilesRecoveryDesktop(
        "windows-cloud-files-recovery-desktop", "windows-cloud-files-recovery-desktop.png",
        NextcloudPresentation.Desktop, "Windows Cloud Files", "Writeback recovery", "Local edits retained after a remote generation conflict",
        MarketingCapturePurpose.Showcase, "windows", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    DesktopStartupSettings(
        "desktop-startup-settings", "desktop-startup-settings.png", NextcloudPresentation.Desktop,
        "File sync", "Desktop settings", "Background sync and start on login enabled",
        MarketingCapturePurpose.StateCoverage, "desktop", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    AdaptiveApp(
        "tables-insights-desktop", "tables-insights-desktop.png", NextcloudPresentation.Desktop,
        "Tables", "Inventory overview and category chart", "Synthetic Tables data",
        MarketingCapturePurpose.Showcase,
        "desktop", "wide", width = 1_440, height = 900, density = 1f,
    ),
    TablesRowsDesktop(
        "tables-rows-desktop", "tables-rows-desktop.png", NextcloudPresentation.Desktop,
        "Tables", "Inventory rows and actions", "Synthetic Tables data",
        MarketingCapturePurpose.StateCoverage,
        "desktop", "wide", width = 1_440, height = 900, density = 1f,
    ),
    TablesRowFormDesktop(
        "tables-row-form-desktop", "tables-row-form-desktop.png", NextcloudPresentation.Desktop,
        "Tables", "Add inventory row", "Synthetic Tables data",
        MarketingCapturePurpose.StateCoverage,
        "desktop", "wide", width = 1_440, height = 900, density = 1f,
    ),
    InlineRecordEditDesktop(
        "inline-record-edit-desktop", "inline-record-edit-desktop.png", NextcloudPresentation.Desktop,
        "Dynamic workspaces", "Edit record in place", "Existing values with inline save and cancel",
        MarketingCapturePurpose.StateCoverage, "desktop", "wide",
        width = 1_440, height = 900, density = 1f,
    ),
    InlineRecordEditMobile(
        "inline-record-edit-mobile", "inline-record-edit-mobile.png", NextcloudPresentation.Adaptive,
        "Dynamic workspaces", "Edit record in place", "Existing values with inline save and cancel",
        MarketingCapturePurpose.StateCoverage, "mobile", "phone-portrait",
        width = 1_080, height = 2_200, density = 2.625f,
    ),
    TablesColumnsDesktop(
        "tables-columns-desktop", "tables-columns-desktop.png", NextcloudPresentation.Desktop,
        "Tables", "Typed table columns", "Synthetic data on the upstream Tables columns route",
        MarketingCapturePurpose.StateCoverage,
        "desktop", "wide", width = 1_440, height = 900, density = 1f,
    ),
    TablesViewsDesktop(
        "tables-views-desktop", "tables-views-desktop.png", NextcloudPresentation.Desktop,
        "Tables", "Saved views", "Synthetic data on the upstream Tables views route",
        MarketingCapturePurpose.StateCoverage,
        "desktop", "wide", width = 1_440, height = 900, density = 1f,
    ),
    TablesSharesDesktop(
        "tables-shares-desktop", "tables-shares-desktop.png", NextcloudPresentation.Desktop,
        "Tables", "Table sharing and permissions", "Synthetic data on the upstream Tables shares route",
        MarketingCapturePurpose.StateCoverage,
        "desktop", "wide", width = 1_440, height = 900, density = 1f,
    ),
    AdaptiveAppMobile(
        "tables-row-form-mobile", "tables-row-form-mobile.png", NextcloudPresentation.Adaptive,
        "Tables", "Add inventory row", "Synthetic Tables data",
        MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-portrait", width = 1_024, height = 2_216, density = 2.625f,
    ),
    AdaptiveAppCollectionMobile(
        "tables-rows-mobile",
        "tables-rows-mobile.png",
        NextcloudPresentation.Adaptive,
        "Tables",
        "Inventory rows and actions",
        "Synthetic Tables data",
        MarketingCapturePurpose.StateCoverage,
        "mobile",
        "phone-portrait",
        width = 1_024,
        height = 2_216,
        density = 2.625f,
    ),
    AdaptiveAppContextMenuMobile(
        "tables-overview-mobile",
        "tables-overview-mobile.png",
        NextcloudPresentation.Adaptive,
        "Tables",
        "Inventory overview and category chart",
        "Synthetic Tables data",
        MarketingCapturePurpose.StateCoverage,
        "mobile",
        "phone-portrait",
        width = 1_024,
        height = 2_216,
        density = 2.625f,
    ),
    TablesColumnsMobile(
        "tables-columns-mobile", "tables-columns-mobile.png", NextcloudPresentation.Adaptive,
        "Tables", "Typed table columns", "Synthetic data on the upstream Tables columns route",
        MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-portrait", width = 1_024, height = 2_216, density = 2.625f,
    ),
    TablesViewsMobile(
        "tables-views-mobile", "tables-views-mobile.png", NextcloudPresentation.Adaptive,
        "Tables", "Saved views", "Synthetic data on the upstream Tables views route",
        MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-portrait", width = 1_024, height = 2_216, density = 2.625f,
    ),
    TablesSharesMobile(
        "tables-shares-mobile", "tables-shares-mobile.png", NextcloudPresentation.Adaptive,
        "Tables", "Table sharing and permissions", "Synthetic data on the upstream Tables shares route",
        MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-portrait", width = 1_024, height = 2_216, density = 2.625f,
    ),
    MailWorkspaceDesktop(
        "mail-workspace-desktop", "mail-workspace-desktop.png", NextcloudPresentation.Desktop,
        "Mail", "Adaptive mailbox workspace", "Inbox message selected", MarketingCapturePurpose.Showcase,
        "desktop", "wide", issue = 54, width = 1_440, height = 900, density = 1f,
    ),
    MailWorkspaceMobile(
        "mail-workspace-mobile", "mail-workspace-mobile.png", NextcloudPresentation.Adaptive,
        "Mail", "Adaptive mailbox workspace", "Inbox message list", MarketingCapturePurpose.Showcase,
        "mobile", "phone-portrait", issue = 54, width = 1_080, height = 1_800, density = 2.625f,
    ),
    MailMessageBodyMobile(
        "mail-message-body-mobile", "mail-message-body-mobile.png", NextcloudPresentation.Adaptive,
        "Mail", "Adaptive mailbox workspace", "Uncached selected message body", MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-portrait", issue = 54, width = 1_080, height = 1_800, density = 2.625f,
    ),
    MailWorkspaceLoadingMobile(
        "mail-workspace-loading-mobile", "mail-workspace-loading-mobile.png", NextcloudPresentation.Adaptive,
        "Mail", "Adaptive mailbox workspace", "Loading inbox", MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-portrait", issue = 54, width = 1_080, height = 1_800, density = 2.625f,
    ),
    MailWorkspaceEmptyMobile(
        "mail-workspace-empty-mobile", "mail-workspace-empty-mobile.png", NextcloudPresentation.Adaptive,
        "Mail", "Adaptive mailbox workspace", "Empty inbox", MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-portrait", issue = 54, width = 1_080, height = 1_800, density = 2.625f,
    ),
    MailWorkspaceErrorDesktop(
        "mail-workspace-error-desktop", "mail-workspace-error-desktop.png", NextcloudPresentation.Desktop,
        "Mail", "Adaptive mailbox workspace", "Message body error", MarketingCapturePurpose.StateCoverage,
        "desktop", "wide", issue = 54, width = 1_440, height = 900, density = 1f,
    ),
    PhotoTimelineRevalidationErrorMobile(
        "photo-timeline-revalidation-error-mobile",
        "photo-timeline-revalidation-error-mobile.png",
        NextcloudPresentation.Adaptive,
        "Photos",
        "Photo timeline",
        "Cached photos with revalidation error",
        MarketingCapturePurpose.StateCoverage,
        "mobile",
        "phone-portrait",
        pullRequest = 246,
        issue = 242,
        width = 1_080,
        height = 1_800,
        density = 2.625f,
    ),
    PhotoTimelineReturnToNewestErrorMobile(
        "photo-timeline-return-to-newest-error-mobile",
        "photo-timeline-return-to-newest-error-mobile.png",
        NextcloudPresentation.Adaptive,
        "Photos",
        "Photo timeline",
        "Older window with failed return to newest",
        MarketingCapturePurpose.StateCoverage,
        "mobile",
        "phone-portrait",
        pullRequest = 246,
        issue = 242,
        width = 1_080,
        height = 1_800,
        density = 2.625f,
    ),
    PhotoTimelineRawRetryMobile(
        "photo-timeline-raw-retry-mobile",
        "photo-timeline-raw-retry-mobile.png",
        NextcloudPresentation.Adaptive,
        "Photos",
        "Photo timeline",
        "Ordinary photos with a RAW retry pending",
        MarketingCapturePurpose.StateCoverage,
        "mobile",
        "phone-portrait",
        pullRequest = 249,
        issue = 248,
        width = 1_080,
        height = 1_800,
        density = 2.625f,
    ),
    PhotoFolderBrowserMobile(
        "photo-folder-browser-mobile",
        "photo-folder-browser-mobile.png",
        NextcloudPresentation.Adaptive,
        "Photos",
        "Folder browser",
        "Trip folder in grid view",
        MarketingCapturePurpose.Showcase,
        "mobile",
        "phone-portrait",
        pullRequest = 245,
        issue = 243,
        width = 1_080,
        height = 1_800,
        density = 2.625f,
    ),
    PhotoFolderBrowserDesktop(
        "photo-folder-browser-desktop",
        "photo-folder-browser-desktop.png",
        NextcloudPresentation.Desktop,
        "Photos",
        "Folder browser",
        "Photo library in list view",
        MarketingCapturePurpose.Showcase,
        "desktop",
        "wide",
        pullRequest = 245,
        issue = 243,
        width = 1_440,
        height = 900,
        density = 1f,
    ),
    RawPreviewLoadingMobile(
        "raw-preview-loading-mobile", "raw-preview-loading-mobile.png",
        NextcloudPresentation.Adaptive, "Photos", "RAW preview",
        "Loading embedded preview", MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-compact", pullRequest = 218, issue = 85,
        width = 1_080, height = 1_200, density = 2.625f,
    ),
    RawPreviewErrorMobile(
        "raw-preview-error-mobile", "raw-preview-error-mobile.png",
        NextcloudPresentation.Adaptive, "Photos", "RAW preview",
        "No usable preview", MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-compact", pullRequest = 218, issue = 85,
        width = 1_080, height = 1_200, density = 2.625f,
    ),
    RawPreviewMemoriesReadyMobile(
        "raw-preview-memories-ready-mobile", "raw-preview-memories-ready-mobile.png",
        NextcloudPresentation.Adaptive, "Photos", "RAW preview",
        "Ready from Memories", MarketingCapturePurpose.Showcase,
        "mobile", "phone-portrait", pullRequest = 218, issue = 85,
        width = 1_080, height = 1_600, density = 2.625f,
    ),
    RawPreviewHighDetailDesktop(
        "raw-preview-high-detail-desktop", "raw-preview-high-detail-desktop.png",
        NextcloudPresentation.Desktop, "Photos", "RAW preview",
        "Embedded high-detail preview", MarketingCapturePurpose.Showcase,
        "desktop", "wide", pullRequest = 218, issue = 85,
        width = 1_440, height = 900, density = 1f,
    ),
    LivePhotoMotionFailureMobile(
        "live-photo-motion-failure-mobile",
        "live-photo-motion-failure-mobile.png",
        NextcloudPresentation.Adaptive,
        "Photos",
        "Live Photo viewer",
        "Still visible after motion decoder failure",
        MarketingCapturePurpose.StateCoverage,
        "mobile",
        "phone-compact",
        pullRequest = 249,
        issue = 182,
        width = 1_080,
        height = 1_200,
        density = 2.625f,
    ),
    NativeTiffPreviewMobile(
        "native-tiff-preview-mobile",
        "native-tiff-preview-mobile.png",
        NextcloudPresentation.Adaptive,
        "Photos",
        "TIFF viewer",
        "Native high-detail preview",
        MarketingCapturePurpose.Showcase,
        "mobile",
        "phone-compact",
        pullRequest = 249,
        issue = 84,
        width = 1_080,
        height = 1_200,
        density = 2.625f,
    ),
    FileShareUserMobile(
        "file-share-user-mobile", "file-share-user-mobile.png", NextcloudPresentation.Adaptive,
        "Files", "Share dialog", "User search results", MarketingCapturePurpose.Showcase,
        "mobile", "phone-portrait", pullRequest = 219, issue = 124,
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    FileShareGroupDesktop(
        "file-share-group-desktop", "file-share-group-desktop.png", NextcloudPresentation.Desktop,
        "Files", "Share dialog", "Group search results", MarketingCapturePurpose.Showcase,
        "desktop", "wide", pullRequest = 219, issue = 124,
        width = 1_440, height = 900, density = 1f,
    ),
    FileShareLoadingMobile(
        "file-share-loading-mobile", "file-share-loading-mobile.png", NextcloudPresentation.Adaptive,
        "Files", "Share dialog", "Loading recipients", MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-portrait", pullRequest = 219, issue = 124,
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    FileShareErrorMobile(
        "file-share-error-mobile", "file-share-error-mobile.png", NextcloudPresentation.Adaptive,
        "Files", "Share dialog", "Recipient search error", MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-portrait", pullRequest = 219, issue = 124,
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    TransferMobilePending(
        "transfer-mobile-pending", "transfer-mobile-pending.png", NextcloudPresentation.Adaptive,
        "Files", "Transfer center", "Pending uploads", MarketingCapturePurpose.Showcase,
        "mobile", "phone-portrait", pullRequest = 220, issue = 168,
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    TransferMobileFailed(
        "transfer-mobile-failed-cached", "transfer-mobile-failed-cached.png",
        NextcloudPresentation.Adaptive, "Files", "Transfer center",
        "Failed upload with cached source", MarketingCapturePurpose.StateCoverage,
        "mobile", "phone-portrait", pullRequest = 220, issue = 168,
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    TransferDesktopActive(
        "transfer-desktop-active", "transfer-desktop-active.png", NextcloudPresentation.Desktop,
        "Files", "Transfer center", "Active transfer", MarketingCapturePurpose.Showcase,
        "desktop", "wide", pullRequest = 220, issue = 168,
        width = 1_280, height = 800, density = 1f,
    ),
    TransferDesktopCompleted(
        "transfer-desktop-completed-page", "transfer-desktop-completed-page.png",
        NextcloudPresentation.Desktop, "Files", "Transfer center",
        "Completed transfer history", MarketingCapturePurpose.Showcase,
        "desktop", "wide", pullRequest = 220, issue = 168,
        width = 1_280, height = 800, density = 1f,
    ),
    DeckBoardDesktop(
        "deck-board-desktop", "deck-board-desktop.png", NextcloudPresentation.Desktop,
        "Deck", "Kanban board", "Ready", MarketingCapturePurpose.Showcase,
        "desktop", "wide", pullRequest = 221, issue = 52,
        width = 1_440, height = 900, density = 1f,
    ),
    DeckBoardMobile(
        "deck-board-mobile", "deck-board-mobile.png", NextcloudPresentation.Adaptive,
        "Deck", "Kanban board", "Ready", MarketingCapturePurpose.Showcase,
        "mobile", "phone-portrait", pullRequest = 221, issue = 52,
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    MusicLibraryAlbumTracksMobile(
        "music-library-album-tracks-mobile", "music-library-album-tracks-mobile.png",
        NextcloudPresentation.Adaptive, "Music", "Album track collection",
        "Ready", MarketingCapturePurpose.Showcase,
        "mobile", "phone-portrait", issue = 56,
        width = 1_080, height = 1_800, density = 2.625f,
    ),
    MusicLibraryPlaybackErrorDesktop(
        "music-library-playback-error-desktop", "music-library-playback-error-desktop.png",
        NextcloudPresentation.Desktop, "Music", "Playback queue",
        "Playback error with queue retained", MarketingCapturePurpose.StateCoverage,
        "desktop", "wide", issue = 56,
        width = 1_440, height = 900, density = 1f,
    ),
    GuideAndroidGettingStartedHome("guide-android-getting-started-home", "guide-android-getting-started-home.png", NextcloudPresentation.Adaptive, "Guides", "Android setup", "Connected mobile Home", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 2_400, density = 2.625f),
    GuideAndroidGettingStartedFiles("guide-android-getting-started-files", "guide-android-getting-started-files.png", NextcloudPresentation.Adaptive, "Guides", "Android setup", "Files and offline state", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 2_400, density = 2.625f),
    GuideAndroidGettingStartedCalendar("guide-android-getting-started-calendar", "guide-android-getting-started-calendar.png", NextcloudPresentation.Adaptive, "Guides", "Android setup", "Native Calendar workspace", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 1_800, density = 2.625f),
    GuideDesktopGettingStartedHome("guide-desktop-getting-started-home", "guide-desktop-getting-started-home.png", NextcloudPresentation.Desktop, "Guides", "Desktop setup", "Connected desktop Home", MarketingCapturePurpose.Showcase, "desktop", "wide", width = 1_440, height = 900, density = 1f),
    GuideDesktopGettingStartedApps("guide-desktop-getting-started-apps", "guide-desktop-getting-started-apps.png", NextcloudPresentation.Desktop, "Guides", "Desktop setup", "Installed app catalog", MarketingCapturePurpose.Showcase, "desktop", "wide", width = 1_440, height = 900, density = 1f),
    GuideDesktopGettingStartedSettings("guide-desktop-getting-started-settings", "guide-desktop-getting-started-settings.png", NextcloudPresentation.Desktop, "Guides", "Desktop setup", "Sync and storage settings", MarketingCapturePurpose.Showcase, "desktop", "wide", width = 1_440, height = 900, density = 1f),
    GuideAndroidOfflineFilesBrowse("guide-android-offline-files-browse", "guide-android-offline-files-browse.png", NextcloudPresentation.Adaptive, "Guides", "Android offline files", "Files and availability", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 2_400, density = 2.625f),
    GuideAndroidOfflineFilesStorage("guide-android-offline-files-storage", "guide-android-offline-files-storage.png", NextcloudPresentation.Adaptive, "Guides", "Android offline files", "System Files storage", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 2_200, density = 2.625f),
    GuideAndroidOfflineFilesTransfers("guide-android-offline-files-transfers", "guide-android-offline-files-transfers.png", NextcloudPresentation.Adaptive, "Guides", "Android offline files", "Pending and failed work", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 1_800, density = 2.625f),
    GuideAndroidFolderSyncLocations("guide-android-folder-sync-locations", "guide-android-folder-sync-locations.png", NextcloudPresentation.Adaptive, "Guides", "Android folder sync", "Device and Nextcloud mapping", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 1_800, density = 2.625f),
    GuideAndroidFolderSyncRules("guide-android-folder-sync-rules", "guide-android-folder-sync-rules.png", NextcloudPresentation.Adaptive, "Guides", "Android folder sync", "Direction and safety rules", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 2_200, density = 2.625f),
    GuideAndroidFolderSyncStatus("guide-android-folder-sync-status", "guide-android-folder-sync-status.png", NextcloudPresentation.Adaptive, "Guides", "Android folder sync", "Schedule, conflict, and health", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 2_200, density = 2.625f),
    GuideLinuxFolderSyncWorkspace("guide-linux-folder-sync-workspace", "guide-linux-folder-sync-workspace.png", NextcloudPresentation.Desktop, "Guides", "Linux folder sync", "Active pair workspace", MarketingCapturePurpose.Showcase, "linux", "wide", width = 1_721, height = 914, density = 1f),
    GuideLinuxFolderSyncLocations("guide-linux-folder-sync-locations", "guide-linux-folder-sync-locations.png", NextcloudPresentation.Desktop, "Guides", "Linux folder sync", "Local and Nextcloud mapping", MarketingCapturePurpose.Showcase, "linux", "wide", width = 1_440, height = 900, density = 1f),
    GuideLinuxFolderSyncRules("guide-linux-folder-sync-rules", "guide-linux-folder-sync-rules.png", NextcloudPresentation.Desktop, "Guides", "Linux folder sync", "Scope and conflict rules", MarketingCapturePurpose.Showcase, "linux", "wide", width = 1_440, height = 900, density = 1f),
    GuideWindowsCloudFilesSettings("guide-windows-cloud-files-settings", "guide-windows-cloud-files-settings.png", NextcloudPresentation.Desktop, "Guides", "Windows Cloud Files", "Sync and storage settings", MarketingCapturePurpose.Showcase, "windows", "wide", width = 1_440, height = 900, density = 1f),
    GuideWindowsCloudFilesStorage("guide-windows-cloud-files-storage", "guide-windows-cloud-files-storage.png", NextcloudPresentation.Desktop, "Guides", "Windows Cloud Files", "File Explorer placeholders", MarketingCapturePurpose.Showcase, "windows", "wide", width = 1_440, height = 900, density = 1f),
    GuideWindowsCloudFilesRecovery("guide-windows-cloud-files-recovery", "guide-windows-cloud-files-recovery.png", NextcloudPresentation.Desktop, "Guides", "Windows Cloud Files", "Guarded writeback recovery", MarketingCapturePurpose.Showcase, "windows", "wide", width = 1_440, height = 900, density = 1f),
    GuideAndroidPhotoBackupFolders("guide-android-photo-backup-folders", "guide-android-photo-backup-folders.png", NextcloudPresentation.Adaptive, "Guides", "Android photo backup", "Media folder discovery", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 2_200, density = 2.625f),
    GuideAndroidPhotoBackupQueue("guide-android-photo-backup-queue", "guide-android-photo-backup-queue.png", NextcloudPresentation.Adaptive, "Guides", "Android photo backup", "Durable transfer queue", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 1_800, density = 2.625f),
    GuideAndroidPhotoBackupLibrary("guide-android-photo-backup-library", "guide-android-photo-backup-library.png", NextcloudPresentation.Adaptive, "Guides", "Android photo backup", "Remote photo library", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 1_800, density = 2.625f),
    GuideAndroidCalendarMonth("guide-android-calendar-month", "guide-android-calendar-month.png", NextcloudPresentation.Adaptive, "Guides", "Android Calendar", "Compact month", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 1_800, density = 2.625f),
    GuideAndroidCalendarAgenda("guide-android-calendar-agenda", "guide-android-calendar-agenda.png", NextcloudPresentation.Adaptive, "Guides", "Android Calendar", "Touch agenda", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 1_800, density = 2.625f),
    GuideAndroidCalendarEdit("guide-android-calendar-edit", "guide-android-calendar-edit.png", NextcloudPresentation.Adaptive, "Guides", "Android Calendar", "Writable event context", MarketingCapturePurpose.Showcase, "android", "phone-portrait", width = 1_080, height = 1_800, density = 2.625f),
    GuideDesktopCalendarMonth("guide-desktop-calendar-month", "guide-desktop-calendar-month.png", NextcloudPresentation.Desktop, "Guides", "Desktop Calendar", "Month and inspector", MarketingCapturePurpose.Showcase, "desktop", "wide", width = 1_440, height = 900, density = 1f),
    GuideDesktopCalendarSources("guide-desktop-calendar-sources", "guide-desktop-calendar-sources.png", NextcloudPresentation.Desktop, "Guides", "Desktop Calendar", "Sources and authority", MarketingCapturePurpose.Showcase, "desktop", "wide", width = 1_440, height = 900, density = 1f),
    GuideDesktopCalendarEdit("guide-desktop-calendar-edit", "guide-desktop-calendar-edit.png", NextcloudPresentation.Desktop, "Guides", "Desktop Calendar", "Writable event context", MarketingCapturePurpose.Showcase, "desktop", "wide", width = 1_440, height = 900, density = 1f),
    GuideDesktopSwitchAppsCatalog("guide-desktop-switch-apps-catalog", "guide-desktop-switch-apps-catalog.png", NextcloudPresentation.Desktop, "Guides", "Desktop app switching", "Installed app catalog", MarketingCapturePurpose.Showcase, "desktop", "wide", width = 1_440, height = 900, density = 1f),
    GuideDesktopSwitchAppsSidebar("guide-desktop-switch-apps-sidebar", "guide-desktop-switch-apps-sidebar.png", NextcloudPresentation.Desktop, "Guides", "Desktop app switching", "Persistent shortcuts", MarketingCapturePurpose.Showcase, "desktop", "wide", width = 1_440, height = 900, density = 1f),
    GuideDesktopSwitchAppsNested("guide-desktop-switch-apps-nested", "guide-desktop-switch-apps-nested.png", NextcloudPresentation.Desktop, "Guides", "Desktop app switching", "Verified nested workspace", MarketingCapturePurpose.Showcase, "desktop", "wide", width = 1_440, height = 900, density = 1f),
}
